interface Region {
  value: string;
  name: string;
}

export const FirstSelectRegion: Region[] = [
  { value: 'default', name: '시/도' },
  { value: '강원', name: '강원' },
  { value: '경기', name: '경기' },
  { value: '경남', name: '경남' },
  { value: '경북', name: '경북' },
  { value: '광주', name: '광주' },
  { value: '대구', name: '대구' },
  { value: '대전', name: '대전' },
  { value: '부산', name: '부산' },
  { value: '세종', name: '세종' },
  { value: '울산', name: '울산' },
  { value: '인천', name: '인천' },
  { value: '전남', name: '전남' },
  { value: '전북', name: '전북' },
  { value: '제주', name: '제주' },
  { value: '충남', name: '충남' },
  { value: '충북', name: '충북' },
];

type SecondSelectRegionType = Record<string, Region[]>;

export const SecondSelectRegion: SecondSelectRegionType = {
  부산: [
    { value: '강서구', name: '강서구' },
    { value: '금정구', name: '금정구' },
    { value: '기장군', name: '기장군' },
    { value: '남구', name: '남구' },
    { value: '동구', name: '동구' },
    { value: '동래구', name: '동래구' },
    { value: '부산진구', name: '부산진구' },
    { value: '북구', name: '북구' },
    { value: '사상구', name: '사상구' },
    { value: '사하구', name: '사하구' },
    { value: '서구', name: '서구' },
    { value: '수영구', name: '수영구' },
    { value: '연제구', name: '연제구' },
    { value: '영도구', name: '영도구' },
    { value: '중구', name: '중구' },
    { value: '해운대구', name: '해운대구' },
  ],
  대구: [
    { value: '군위군', name: '군위군' },
    { value: '남구', name: '남구' },
    { value: '달서구', name: '달서구' },
    { value: '달성군', name: '달성군' },
    { value: '동구', name: '동구' },
    { value: '북구', name: '북구' },
    { value: '서구', name: '서구' },
    { value: '수성구', name: '수성구' },
    { value: '중구', name: '중구' },
  ],
  인천: [
    { value: '강화군', name: '강화군' },
    { value: '계양구', name: '계양구' },
    { value: '남동구', name: '남동구' },
    { value: '동구', name: '동구' },
    { value: '미추홀구', name: '미추홀구' },
    { value: '부평구', name: '부평구' },
    { value: '서구', name: '서구' },
    { value: '연수구', name: '연수구' },
    { value: '옹진군', name: '옹진군' },
    { value: '중구', name: '중구' },
  ],
  광주: [
    { value: '광산구', name: '광산구' },
    { value: '남구', name: '남구' },
    { value: '동구', name: '동구' },
    { value: '북구', name: '북구' },
    { value: '서구', name: '서구' },
  ],
  대전: [
    { value: '대덕구', name: '대덕구' },
    { value: '동구', name: '동구' },
    { value: '서구', name: '서구' },
    { value: '유성구', name: '유성구' },
    { value: '중구', name: '중구' },
  ],
  울산: [
    { value: '남구', name: '남구' },
    { value: '동구', name: '동구' },
    { value: '북구', name: '북구' },
    { value: '울주군', name: '울주군' },
    { value: '중구', name: '중구' },
  ],
  세종: [{ value: '-', name: '-' }],
  경기: [
    { value: '가평', name: '가평' },
    { value: '고양', name: '고양' },
    { value: '과천', name: '과천' },
    { value: '광명', name: '광명' },
    { value: '광주', name: '광주' },
    { value: '구리', name: '구리' },
    { value: '군포', name: '군포' },
    { value: '김포', name: '김포' },
    { value: '남양주', name: '남양주' },
    { value: '동두천', name: '동두천' },
    { value: '부천', name: '부천' },
    { value: '성남', name: '성남' },
    { value: '수원', name: '수원' },
    { value: '시흥', name: '시흥' },
    { value: '안산', name: '안산' },
    { value: '안성', name: '안성' },
    { value: '안양', name: '안양' },
    { value: '양주', name: '양주' },
    { value: '양평', name: '양평' },
    { value: '여주', name: '여주' },
    { value: '연천', name: '연천' },
    { value: '오산', name: '오산' },
    { value: '용인', name: '용인' },
    { value: '의왕', name: '의왕' },
    { value: '의정부', name: '의정부' },
    { value: '이천', name: '이천' },
    { value: '파주', name: '파주' },
    { value: '평택', name: '평택' },
    { value: '포천', name: '포천' },
    { value: '하남', name: '하남' },
    { value: '화성', name: '화성' },
  ],
  강원: [
    { value: '강릉', name: '강릉' },
    { value: '고성', name: '고성' },
    { value: '동해', name: '동해' },
    { value: '삼척', name: '삼척' },
    { value: '속초', name: '속초' },
    { value: '양구', name: '양구' },
    { value: '양양', name: '양양' },
    { value: '영월', name: '영월' },
    { value: '원주', name: '원주' },
    { value: '인제', name: '인제' },
    { value: '정선', name: '정선' },
    { value: '철원', name: '철원' },
    { value: '춘천', name: '춘천' },
    { value: '태백', name: '태백' },
    { value: '평창', name: '평창' },
    { value: '홍천', name: '홍천' },
    { value: '화천', name: '화천' },
    { value: '횡성', name: '횡성' },
  ],
  충북: [
    { value: '괴산', name: '괴산' },
    { value: '단양', name: '단양' },
    { value: '보은', name: '보은' },
    { value: '영동', name: '영동' },
    { value: '옥천', name: '옥천' },
    { value: '음성', name: '음성' },
    { value: '제천', name: '제천' },
    { value: '증평', name: '증평' },
    { value: '진천', name: '진천' },
    { value: '청주', name: '청주' },
    { value: '충주', name: '충주' },
  ],
  충남: [
    { value: '계룡', name: '계룡' },
    { value: '공주', name: '공주' },
    { value: '금산', name: '금산' },
    { value: '논산', name: '논산' },
    { value: '당진', name: '당진' },
    { value: '보령', name: '보령' },
    { value: '부여', name: '부여' },
    { value: '서산', name: '서산' },
    { value: '서천', name: '서천' },
    { value: '아산', name: '아산' },
    { value: '예산', name: '예산' },
    { value: '천안', name: '천안' },
    { value: '청양', name: '청양' },
    { value: '태안', name: '태안' },
    { value: '홍성', name: '홍성' },
  ],
  전북: [
    { value: '고창', name: '고창' },
    { value: '군산', name: '군산' },
    { value: '김제', name: '김제' },
    { value: '남원', name: '남원' },
    { value: '무주', name: '무주' },
    { value: '부안', name: '부안' },
    { value: '순창', name: '순창' },
    { value: '완주', name: '완주' },
    { value: '익산', name: '익산' },
    { value: '임실', name: '임실' },
    { value: '장수', name: '장수' },
    { value: '전주', name: '전주' },
    { value: '정읍', name: '정읍' },
    { value: '진안', name: '진안' },
  ],
  전남: [
    { value: '강진', name: '강진' },
    { value: '고흥', name: '고흥' },
    { value: '곡성', name: '곡성' },
    { value: '광양', name: '광양' },
    { value: '구례', name: '구례' },
    { value: '나주', name: '나주' },
    { value: '담양', name: '담양' },
    { value: '목포', name: '목포' },
    { value: '무안', name: '무안' },
    { value: '보성', name: '보성' },
    { value: '순천', name: '순천' },
    { value: '신안', name: '신안' },
    { value: '여수', name: '여수' },
    { value: '영광', name: '영광' },
    { value: '영암', name: '영암' },
    { value: '완도', name: '완도' },
    { value: '장성', name: '장성' },
    { value: '장흥', name: '장흥' },
    { value: '진도', name: '진도' },
    { value: '함평', name: '함평' },
    { value: '해남', name: '해남' },
    { value: '화순', name: '화순' },
  ],
  경북: [
    { value: '경산', name: '경산' },
    { value: '경주', name: '경주' },
    { value: '고령', name: '고령' },
    { value: '구미', name: '구미' },
    { value: '김천', name: '김천' },
    { value: '문경', name: '문경' },
    { value: '봉화', name: '봉화' },
    { value: '상주', name: '상주' },
    { value: '성주', name: '성주' },
    { value: '안동', name: '안동' },
    { value: '영덕', name: '영덕' },
    { value: '영양', name: '영양' },
    { value: '영주', name: '영주' },
    { value: '영천', name: '영천' },
    { value: '예천', name: '예천' },
    { value: '울릉', name: '울릉' },
    { value: '울진', name: '울진' },
    { value: '의성', name: '의성' },
    { value: '청도', name: '청도' },
    { value: '청송', name: '청송' },
    { value: '칠곡', name: '칠곡' },
    { value: '포항', name: '포항' },
  ],
  경남: [
    { value: '거제', name: '거제' },
    { value: '거창', name: '거창' },
    { value: '고성', name: '고성' },
    { value: '김해', name: '김해' },
    { value: '남해', name: '남해' },
    { value: '밀양', name: '밀양' },
    { value: '사천', name: '사천' },
    { value: '산청', name: '산청' },
    { value: '양산', name: '양산' },
    { value: '의령', name: '의령' },
    { value: '진주', name: '진주' },
    { value: '창녕', name: '창녕' },
    { value: '창원', name: '창원' },
    { value: '통영', name: '통영' },
    { value: '하동', name: '하동' },
    { value: '함안', name: '함안' },
    { value: '함양', name: '함양' },
    { value: '합천', name: '합천' },
  ],
  제주: [
    { value: '서귀포', name: '서귀포' },
    { value: '제주', name: '제주' },
  ],
};
